version: "3.8"
services:
  envoy:
    image: envoyproxy/envoy-dev:db7b43a0dd63cee0e898268830b17b8938cff5f9
    command: envoy -c /etc/envoy.yaml
    volumes:
      - "./envoy/envoy-static.yaml:/etc/envoy.yaml:ro"
    ports:
      - "9000:9000"
      - "8000:8000"

  xdsserver:
    build: ./cmd/xdsserver
    ports:
      - "12345:12345"

  server:
    build: ./cmd/server
    ports:
      - "8080:8080"
